config/routes.rb
TwitterClone::Application.routes.draw do
  root to: 'users#home'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users, :except => [:index, :update, :edit]
  resources :sessions
  resources :tweets

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :message, presence: true

  def find_tweeted_handles
  	users_to_email = []
  	handles_tweeted = self.message.scan(/@[A-z]*\b/)
  	if handles_tweeted
			handles_tweeted.map { | handle | handle.slice!(0) }
			handles_tweeted.each do | handle |
				users_to_email << User.find_by(handle: handle)
			end
  	end
  	users_to_email
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :tweets
  has_many :follows

  valid_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :handle, presence: true
  validates :email,
            presence: true,
            format: { with: valid_email_regex },
            uniqueness: true,
            case_sensitive: false
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_digest, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_handle(params[:handle])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Logged in!"
      redirect_to user_path(current_user)
    else
      flash.now.alert = "Email or Password is invalid."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out!"
    redirect_to root_path
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.save
      @tweet.find_tweeted_handles.each do | user_to_email |
        UserMailer.tagged_notification(user_to_email, @tweet).deliver
      end
      redirect_to tweets_path
    else
      flash[:alert] = "Your tweet was not saved - please try again"
      render 'new'
    end
  end

private

  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def home
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      session[:user_id] = @user.id
      flash[:notice] = "Thank you for signing up!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @tweets = Tweet.where(user_id: @user.id)
  end

private

  def user_params
    params.require(:user).permit(:handle,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="red error_messages">
    <h2>Invalid email or password</h2>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer navbar navbar-fixed-bottom">
  <div class="container">

  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header navbar navbar-fixed-top">
  <div class="container-inner">
    <ul class="brand pull-left">
      <li><%= link_to "Tweeter", tweets_path %></li>
    </ul>
    <ul class="header-links pull-right">
      <% if current_user %>
        <li><%= link_to "Create a Tweet", new_tweet_path %></li>
        <li>Logged in as <span class="orange"><%= link_to current_user.handle, user_path(current_user) %></span></li>
        <li><%= link_to "Log Out", logout_path %></li>
      <% else %>
        <li><%= link_to "Login", login_path %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <title><%= content_for?(:title) ? yield(:title)+" | Tweeter" : "Tweeter" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Acme|Roboto+Condensed:400,700|Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container flash">
  <span class="green"><%= flash[:notice] %></span>
  <span class="red"><%= flash[:alert] %></span>
</div>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/tweets/index.html.erb
<%= content_for(:title, "Tweets") %>

<div class="all-tweets container">
  <div class="row">
    <h1>Tweeter</h1>

    <ul>
      <% @tweets.each do | tweet | %>
        <li class="tweet-message"><%= tweet.message %></li><br />
        <li class="tweet-user">Tweeted by <%= link_to tweet.user.handle, user_path(tweet.user) %></li><br /><br />
      <% end %>
    </ul>

  </div>
</div>

app/views/tweets/new.html.erb
<%= content_for(:title, "New Tweet") %>

<div class="main-page container">
  <div class="row">
    <h1>Write a new Tweet!</h1>

    <%= render("layouts/errors", :object => @tweet) %>

    <%= form_for @tweet do |f| %>
      <div class="form-group">
        <%= f.label :message %></br>
        <%= f.text_field :message %>
      </div>
      <div class="form-group">
        <%= f.hidden_field :user_id, :value => current_user.id %></br>
        <%= f.submit(:class => "btn btn-primary") %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/home.html.erb
<%= content_for(:title, "Home") %>

<div class="main-page container">
  <h1>Share every. single. moment. with Tweeter</h1>
  <div class="row">
    <div class="photo">
      <%= image_tag("tweeter-bird.png", height: '40%', width: '40%', class: "tweeter-bird") %>
    </div>
  </div>
  <%= link_to "Sign up for Tweeter", signup_path, class: "signup-button btn btn-default" %>
</div>

app/views/users/new.html.erb
<%= content_for(:title, "Sign up") %>

<div class="signup-form container">
  <h1>Sign Up</h1>

  <%= render("layouts/errors", :object => @user) %>

  <%= form_for @user do |f| %>
    <div class="field">
      <%= f.label :handle %><br />
      <%= f.text_field :handle, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password, class: 'form-control'  %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class="actions"><%= submit_tag "Sign up" %></div>
  <% end %>

</div>

app/views/users/show.html.erb
<div class="user-page container">
  <div class="row">
    <h1>Welcome <%= @user.handle %></h1>

    <ul>
      <% @tweets.each do | tweet | %>
        <li class="user-handle"><%= tweet.user.handle %> |
          <%= tweet.created_at.strftime("%B %d, %Y") %>
        </li><br />
        <li class="user-message"><%= tweet.message %></li><br /><br />
      <% end %>
    </ul>

  </div>
</div>